title: RI-handbook
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  RI-handbook
url: "https://remoteindian.github.io"
github_username: remoteindian

theme: just-the-docs
plugins:
  - jekyll-feed

# site settings
logo: "/assets/brand.png"
favicon_ico: "/assets/favicon.ico"
nav_enabled: true
heading_anchors: true
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"
mermaid:
  version: "9.1.3"
callouts:
  warning:
    title: Warning
    color: red
# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/remoteindian/ri-handbook"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"
